set(SOURCES
	src/ChatUI.h
	include/ChatClient.h
	src/main.cpp
	src/ChatUI.cpp
	src/ChatClient.cpp
	src/PCH.h
	src/KeyHandler.h
	src/KeyHandler.cpp
	src/PrismaUI_F4_API.h
	src/UserID.h
	src/UserID.cpp
)
